/**
 * Shared error codes for the Swee ecosystem.
 * Both SuiAgent and SealChat use these for consistent error handling.
 */
export enum SweeErrorCode {
  // Network
  NETWORK_ERROR = 'NETWORK_ERROR',
  RPC_TIMEOUT = 'RPC_TIMEOUT',
  // SEAL
  SEAL_ENCRYPT_FAILED = 'SEAL_ENCRYPT_FAILED',
  SEAL_DECRYPT_FAILED = 'SEAL_DECRYPT_FAILED',
  SEAL_SESSION_EXPIRED = 'SEAL_SESSION_EXPIRED',
  SEAL_ACCESS_DENIED = 'SEAL_ACCESS_DENIED',
  // Walrus
  WALRUS_UPLOAD_FAILED = 'WALRUS_UPLOAD_FAILED',
  WALRUS_DOWNLOAD_FAILED = 'WALRUS_DOWNLOAD_FAILED',
  // Wallet
  WALLET_CREATION_FAILED = 'WALLET_CREATION_FAILED',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  SPONSORSHIP_FAILED = 'SPONSORSHIP_FAILED',
  // Budget
  BUDGET_EXCEEDED = 'BUDGET_EXCEEDED',
  // Generic
  INVALID_ARGUMENT = 'INVALID_ARGUMENT',
}
